//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void beep(); \
	void stop_motors(); \
	void throttle_0(const float n); \
	void throttle_1(const float n); \
	void throttle_2(const float n); \
	void throttle_3(const float n); \
	void receiveEvent(int countToRead); \
	void requestEvent(); \
	void setup(); \
	void loop(); \

